version: 2
jobs:
  build:
    docker:
      - image: node:7.10
    steps:
      - checkout
      - run: mkdir ./server/node_modules
      - run: npm --prefix /server install /server
      - run: ./run.sh &> /dev/null & npm --prefix ./server test
      - run: pkill node
